name: Build and deploy ASP.Net Core app to Azure Web App - dating-app-course

on: 
  push:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment (qa, uat, sit, release)'
        required: true
        default: 'release'
        type: choice
        options:
          - qa
          - uat
          - sit
          - release

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Build with dotnet
        run: dotnet build --configuration ${{ github.event.inputs.environment || 'Release' }}

      - name: dotnet publish
        run: dotnet publish -c ${{ github.event.inputs.environment || 'Release' }} -o ./publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy-sit:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy to SIT
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'aviapp-sit'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_SIT }}
          package: .

  deploy-qa:
    runs-on: windows-latest
    needs: deploy-sit
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy to QA
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'aviapp-qa'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_QA }}
          package: .

  deploy-uat:
    runs-on: windows-latest
    needs: deploy-qa
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy to UAT
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'aviapp-uat'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_UAT }}
          package: .

